### ISSUE TITLE
boolean value causing issue with list radio type

### ISSUE THREAD

**Issue by jaideepdas** [formly-js/vue-formly-bootstrap#8]
So using the following options in list with type radio is causing issue when you select 'No'
`[{
      label: 'Yes',
      value: true
    }, {
      label: 'No',
      value: false
    }]`
On selecting 'Yes' its setting model value correctly which is true but if select no then its setting model value to then entire choice object which is `{label: 'No', value: false}` which seems very odd as I was looking at the component source code couldn't pin point the issue

**Comment by jaideepdas** [comment]
I have found the problem this condition (`option.value || option`) in value
`<input v-if="to.inputType == 'radio'" type="radio" v-model="model[field.key]" :value="option.value || option" @blur="onBlur" @focus="onFocus" @click="onClick" @change="onChange" @keyup="onKeyup" @keydown="onKeydown" v-formly-atts="to.atts" :class="to.classes">`

**Comment by matt-sanders** [comment]
thanks @jaideepdas I'll release a fix soon

**Comment by jaideepdas** [comment]
@matt-sanders great thanks once you do please so share a comment over here

**Comment by matt-sanders** [comment]
@jaideepdas will do, I'm just working on some SSR compatibility at the moment so will add this in after that. Shouldn't be too far off.

**Comment by jaideepdas** [comment]
hi @matt-sanders any update on this

**Comment by matt-sanders** [comment]
@jaideepdas yup, it's coming very soon. I've actually built the update I just want to do a little more testing and have had a very very busy week. I'll do my best to get it out this week but otherwise it'll be next week. You could also check out the [ssr branch](https://github.com/formly-js/vue-formly-bootstrap/tree/ssr) if you wanted to start using it in your project early.
